INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em agente comunitário de saúde','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em agrimensura','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em aquicultura','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em desenvolvimento de sistemas','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em design de móveis e interiores','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em edificações','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em eletrônica','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em eletrotécnica','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em estradas','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em eventos','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em geodésia e cartografia','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em hospedagem','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em mecânica','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em metalurgia','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em mineração','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em pesca','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em química','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em saneamento','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em segurança do trabalho','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em telecomunicação','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em turismo','técnico');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('engenharia de controle e automação', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('engenharia de materiais', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('engenharia elétrica', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('licenciatura em ciências biológicas', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('licenciatura em física', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('licenciatura em geografia', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('licenciatura em história', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('licenciatura em letras - língua portuguesa', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('licenciatura em matemática', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('licenciatura em pedagogia', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('licenciatura em química', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('tecnologia em análise e desenvolvimento de sistemas', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('tecnologia em eletrotécnica industrial', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('tecnologia em gestão de saúde', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('tecnologia em gestão hospitalar', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('tecnologia em gestão pública', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('tecnologia em saneamento ambiental', 'graduação');
INSERT INTO `cursos` (`nome_curso`, `modalidade_curso`) VALUES ('tecnologia em sistemas de telecomunicações', 'graduação');
