INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em agente comunitário de saúde','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em agrimensura','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em aquicultura','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em desenvolvimento de sistemas','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em design de móveis e interiores','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em edificações','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em eletrônica','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em eletrotécnica','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em estradas','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em eventos','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em geodésia e cartografia','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em hospedagem','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em mecânica','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em metalurgia','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em mineração','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em pesca','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em química','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em saneamento','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em segurança do trabalho','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em telecomunicação','técnico');
INSERT INTO `t76cty90vexcuq57`.`cursos` (`nome_curso`, `modalidade_curso`) VALUES ('técnico em turismo','técnico');
